name: Deploy to beanstalk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - run: git checkout ${{ github.ref_name }}
        working-directory: ./traccar-web
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - run: ./gradlew build
      - run: zip -r deploy.zip . -x '*.git*' -x 'src/*' -x '.gradle/*' -x 'gradle/*'
      - uses: einaregilsson/beanstalk-deploy@v21
        name: deploy eb
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: traccar-tf
          environment_name: Traccar-env
          version_label: ${{ github.run_number }}
          region: eu-west-3
          deployment_package: deploy.zip
